config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root to: 'home#index'

  resources :agent_rooms, only: [:new, :create, :show, :index]
  resources :listings, only: [:index, :show]
  get '/start' => 'agent_rooms#start'
  root 'agent_rooms#index'

  mount ActionCable.server => '/cable'
end

app/models/agent_room.rb
# == Schema Information
#
# Table name: agent_rooms
#
#  id         :integer          not null, primary key
#  title      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AgentRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_one :agent

  after_create :create_agent

  private

  def create_agent
    self.build_agent(name: 'Agent Smith').save
  end
end

app/controllers/agent_rooms_controller.rb
class AgentRoomsController < ApplicationController
  def index
    @agent_rooms = AgentRoom.all
  end

  def new
    @agent_room = AgentRoom.new
  end

  def show
    @agent_room = AgentRoom.find_by(id: params[:id])
    @messages = @agent_room.messages
    @message = Message.new
  end

  def create
    @agent_room = current_user.agent_rooms.build(agent_room_params)
    if @agent_room.save
      flash[:success] = 'Agent room added!'
      redirect_to agent_rooms_path
    else
      render 'new'
    end
  end

  def start
    @agent_room = current_user.agent_rooms.build(title: 'Agent Smith')

    @agent_room.save
    redirect_to agent_room_path(@agent_room)
  end

  private

  def agent_room_params
    params.require(:agent_room).permit(:title)
  end
end

app/views/agent_rooms/_agent_room.html.erb
<li><%= link_to "Enter #{agent_room.title}", agent_room_path(agent_room) %></li>

app/views/agent_rooms/index.html.erb
<h1>Agent rooms</h1>

<!--<p class="lead">< link_to 'New agent room', new_agent_room_path, class: 'btn btn-primary' ></p>-->

<p class="lead"><%= link_to 'Get Started', start_path, class: 'btn btn-primary' %></p>
<ul>
  <%= render @agent_rooms %>
</ul>

app/views/agent_rooms/new.html.erb
<h1>Add agent room</h1>

<%= form_for @agent_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/agent_rooms/show.html.erb
<div class="chat_window">
  <div class="top_menu">
    <div class="buttons">
      <div class="button close"></div>
      <div class="button minimize"></div>
      <div class="button maximize"></div>
    </div>
    <div class="title">Chat with <%= @agent_room.agent.name %></div>
  </div>
  <ul class="messages" id="messages" data-agent-room-id="<%= @agent_room.id %>">
    <%= render @messages %>
  </ul>

  <div class="bottom_wrapper clearfix">
    <%= form_for @message, url: '#' do |f| %>
      <div class="message_input_wrapper">
        <%= f.text_area :body, class: 'message_input', placehlder: "Type your message here..." %>
      </div>
      <%= f.button '', class: "send_message" do %>
          <div class="icon"></div>
          <div class="text">Send</div>
      <% end %>
    <% end %>
  </div>

</div>